/* ai_detector.c - deterministic linear model with sigmoid, plus explainability
 * We simulate a trained model by embedding precomputed weights (from a toy trainer).
 * Features used:
 *  f0 = xray_sig
 *  f1 = metal_val
 *  f2 = weight_anomaly
 *  f3 = watchlist_score
 *  f4 = behavior_score
 * The model computes s = w0*f0 + w1*f1 + ... + b; p = sigmoid(s)
 * For explainability we return per-feature contributions (w_i * f_i) and bias term.
 */

#include "ai_detector.h"
#include <math.h>
#include <stdio.h>

// Pretrained weights (toy values for demo). In practice, generated by a trainer.
static const double WEIGHTS[5] = { 2.2, 1.8, 1.4, 3.5, 1.0 };
static const double BIAS = -1.5;

static double sigmoid(double x) { return 1.0 / (1.0 + exp(-x)); }

double ai_infer(double xray_sig, double metal_val, double weight_anomaly, double watchlist, double behavior) {
    double s = WEIGHTS[0]*xray_sig + WEIGHTS[1]*metal_val + WEIGHTS[2]*weight_anomaly + WEIGHTS[3]*watchlist + WEIGHTS[4]*behavior + BIAS;
    return sigmoid(s);
}

double ai_explain_event(const double features[5], double contributions[6]) {
    double s = BIAS; contributions[5] = BIAS; // bias term index 5
    for (int i=0;i<5;i++) { contributions[i] = WEIGHTS[i] * features[i]; s += contributions[i]; }
    double p = sigmoid(s);
    return p;
}

void ai_explain(const Event *e, double out_contrib[6]) {
    double f[5] = { e->xray_sig, e->metal_val, e->weight_anomaly, e->watchlist_score, e->behavior_score };
    ai_explain_event(f, out_contrib);
}
